import Link from "next/link";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Investment Disclaimer — LootVue",
  description: "Important disclaimers regarding LootVue's real estate analysis, data accuracy, and regulatory status.",
};

export default function DisclaimerPage() {
  return (
    <div className="min-h-screen bg-surface text-content-primary">

      {/* ── NAV ── */}
      <nav className="fixed top-0 left-0 right-0 z-50 backdrop-blur-xl bg-surface/80 border-b border-white/[0.06]">
        <div className="max-w-7xl mx-auto flex items-center justify-between px-6 h-16">
          <Link href="/" className="flex items-center gap-2">
            <span className="text-gold-light text-lg font-serif">LV</span>
            <span className="font-display font-bold text-white tracking-wider text-sm">LOOTVUE</span>
          </Link>
          <div className="flex items-center gap-3">
            <Link href="/login" className="btn-ghost text-sm hidden sm:inline-flex">Log in</Link>
            <Link href="/signup" className="btn-primary btn-sm">Get Started</Link>
          </div>
        </div>
      </nav>

      {/* ── CONTENT ── */}
      <main className="pt-32 pb-24 px-6">
        <div className="max-w-3xl mx-auto">

          <header className="mb-16">
            <p className="text-gold-light text-xs font-semibold tracking-[0.12em] uppercase mb-3">Legal</p>
            <h1 className="font-display text-3xl md:text-4xl font-bold text-white tracking-tight mb-4">
              Investment Disclaimer
            </h1>
            <p className="text-content-secondary text-sm">
              Last updated: March 15, 2026
            </p>
          </header>

          {/* ── PROMINENT WARNING BANNER ── */}
          <div className="card border-rose/30 p-6 md:p-8 mb-12 relative overflow-hidden">
            <div className="absolute inset-0 bg-gradient-to-br from-rose/[0.06] to-transparent pointer-events-none" />
            <div className="relative">
              <h2 className="text-rose-light font-bold text-2xl md:text-3xl uppercase tracking-wide mb-4">
                Not Investment Advice
              </h2>
              <p className="text-content-primary text-base leading-relaxed font-medium">
                LootVue is a data analytics platform. It does not provide personalized investment advice, financial planning, or recommendations to buy or sell specific properties. All information, analyses, scores, and verdicts presented by the Service are for informational and educational purposes only.
              </p>
            </div>
          </div>

          <div className="space-y-10 text-sm text-content-secondary leading-relaxed">

            {/* 1 */}
            <section>
              <h2 className="text-xl font-semibold text-white mb-4">Regulatory Status</h2>
              <p>
                LootVue Inc. is not registered as an investment adviser with the U.S. Securities and Exchange Commission (SEC) or with any state securities regulatory authority. The company does not hold a real estate broker license and does not act as a broker, dealer, or fiduciary. LootVue does not manage client assets, execute transactions, or hold funds on behalf of users. No fiduciary relationship is created between LootVue and its users through use of the Service.
              </p>
            </section>

            {/* 2 */}
            <section>
              <h2 className="text-xl font-semibold text-white mb-4">Nature of Analysis and Outputs</h2>
              <p className="mb-4">
                The analysis, scores, verdicts, and recommendations generated by LootVue are based on publicly available data, licensed third-party data, and proprietary algorithms. They represent computational outputs derived from mathematical models and statistical analysis. They should not be construed as guarantees of future performance, professional opinions, or personalized advice tailored to your specific financial situation, objectives, or risk tolerance.
              </p>
              <div className="card p-5 space-y-4">
                <div className="flex items-start gap-3">
                  <div className="w-6 h-6 rounded-full bg-rose-muted flex items-center justify-center flex-shrink-0 mt-0.5">
                    <span className="text-rose-light text-xs font-bold">1</span>
                  </div>
                  <p>
                    <span className="text-content-primary font-semibold">The &ldquo;confidence levels&rdquo; shown are statistical outputs, not certainties.</span> A confidence level of 87% does not mean there is an 87% chance the investment will succeed. It represents the model&rsquo;s internal assessment of data quality and consistency across multiple analytical dimensions. Actual outcomes may differ materially from model predictions.
                  </p>
                </div>
                <div className="flex items-start gap-3">
                  <div className="w-6 h-6 rounded-full bg-rose-muted flex items-center justify-center flex-shrink-0 mt-0.5">
                    <span className="text-rose-light text-xs font-bold">2</span>
                  </div>
                  <p>
                    <span className="text-content-primary font-semibold">The &ldquo;verdicts&rdquo; (BUY, HOLD, AVOID) are algorithmic classifications, not personal recommendations.</span> These labels are generated by proprietary scoring models and reflect the model&rsquo;s assessment of data patterns. They do not account for your personal financial situation, tax circumstances, investment timeline, risk tolerance, or other individual factors that should inform investment decisions.
                  </p>
                </div>
                <div className="flex items-start gap-3">
                  <div className="w-6 h-6 rounded-full bg-rose-muted flex items-center justify-center flex-shrink-0 mt-0.5">
                    <span className="text-rose-light text-xs font-bold">3</span>
                  </div>
                  <p>
                    <span className="text-content-primary font-semibold">Scores and rankings are relative measures, not absolute guarantees.</span> A property scoring 92/100 does not mean it is a &ldquo;guaranteed good investment.&rdquo; It means that, based on the data available to the model at the time of analysis, it scores well relative to other properties on the specific metrics measured. Markets change. Data can be wrong. Models have limitations.
                  </p>
                </div>
              </div>
            </section>

            {/* 3 */}
            <section>
              <h2 className="text-xl font-semibold text-white mb-4">No Guarantee of Performance</h2>
              <p className="mb-4">
                Past performance of the analysis system does not guarantee future results. Historical accuracy of scores, verdicts, or predictions does not ensure that future outputs will be equally accurate. Real estate markets are influenced by numerous factors that are inherently unpredictable, including but not limited to: macroeconomic conditions, interest rate changes, legislative and regulatory changes, natural disasters, pandemics, local market shifts, and idiosyncratic property-level events.
              </p>
              <p>
                Any backtested or historical performance data presented on the platform is hypothetical and subject to inherent limitations. Backtested results do not represent actual trading or investment outcomes and may not account for all factors that affect real-world performance.
              </p>
            </section>

            {/* 4 */}
            <section>
              <h2 className="text-xl font-semibold text-white mb-4">Investment Risk</h2>
              <div className="card border-amber/20 p-5 mb-4">
                <p className="text-amber-light font-bold text-sm mb-3">Risk Warning</p>
                <p className="text-content-secondary">
                  Real estate investing involves significant risk, including the potential loss of your entire principal investment. Property values can decline. Rental income can decrease or cease entirely. Unexpected expenses can arise. Financing terms can change. Liquidity is limited — you may not be able to sell a property quickly or at a price you consider acceptable.
                </p>
              </div>
              <p>
                The risks of real estate investing include, but are not limited to: market risk (property values declining), liquidity risk (inability to sell quickly), credit risk (tenant default), interest rate risk (changes in borrowing costs), operational risk (unexpected maintenance, vacancies, management issues), regulatory risk (zoning changes, rent control, tax law changes), environmental risk (contamination, natural disasters, climate-related events), and concentration risk (over-allocation to a single market or property type). These risks can result in partial or total loss of invested capital.
              </p>
            </section>

            {/* 5 */}
            <section>
              <h2 className="text-xl font-semibold text-white mb-4">Professional Advice Required</h2>
              <div className="card border-gold/20 p-5">
                <p className="text-gold-light font-bold text-sm mb-3">Before Making Any Investment Decision</p>
                <p className="text-content-secondary mb-4">
                  Always consult with qualified professionals who can evaluate your specific circumstances:
                </p>
                <ul className="space-y-3">
                  <li className="flex items-start gap-3">
                    <span className="text-gold-light font-mono text-xs mt-0.5">01</span>
                    <p><span className="text-content-primary font-semibold">A qualified financial advisor</span> who can assess whether a real estate investment is appropriate given your overall financial situation, goals, income, net worth, existing portfolio allocations, and risk tolerance.</p>
                  </li>
                  <li className="flex items-start gap-3">
                    <span className="text-gold-light font-mono text-xs mt-0.5">02</span>
                    <p><span className="text-content-primary font-semibold">A real estate attorney</span> who can review purchase agreements, title reports, zoning compliance, HOA documents, lease agreements, and other legal aspects of the transaction in your jurisdiction.</p>
                  </li>
                  <li className="flex items-start gap-3">
                    <span className="text-gold-light font-mono text-xs mt-0.5">03</span>
                    <p><span className="text-content-primary font-semibold">A tax professional</span> (CPA or enrolled agent) who can advise on the tax implications of real estate ownership, depreciation, 1031 exchanges, passive activity rules, and state/local tax obligations specific to your situation.</p>
                  </li>
                  <li className="flex items-start gap-3">
                    <span className="text-gold-light font-mono text-xs mt-0.5">04</span>
                    <p><span className="text-content-primary font-semibold">A licensed property inspector</span> who can physically assess the structural integrity, mechanical systems, environmental hazards, and overall condition of any property you are considering purchasing.</p>
                  </li>
                  <li className="flex items-start gap-3">
                    <span className="text-gold-light font-mono text-xs mt-0.5">05</span>
                    <p><span className="text-content-primary font-semibold">A licensed insurance professional</span> who can evaluate appropriate coverage for property damage, liability, flood, earthquake, and other risks specific to the property and location.</p>
                  </li>
                </ul>
              </div>
            </section>

            {/* 6 */}
            <section>
              <h2 className="text-xl font-semibold text-white mb-4">Data Accuracy and Limitations</h2>
              <p className="mb-4">
                Data sources used by LootVue may be incomplete, delayed, or inaccurate. Real estate data is inherently fragmented across multiple sources, jurisdictions, and recording systems. While we aggregate data from reputable sources including the Federal Reserve (FRED), U.S. Census Bureau, Bureau of Labor Statistics, ATTOM Property Data, RentCast, and others, we cannot guarantee the accuracy, completeness, or timeliness of any data point.
              </p>
              <p className="mb-4">
                Specific data limitations include but are not limited to:
              </p>
              <ul className="list-disc list-inside space-y-2 pl-2 mb-4">
                <li>Property transaction records may lag by weeks or months depending on the county recording office.</li>
                <li>Rental estimates are based on comparable listings and reported rents, which may not reflect actual rents achieved.</li>
                <li>Tax assessments may not reflect current market values and can change unpredictably.</li>
                <li>Demographic and economic data from Census and BLS sources is often reported on a delayed schedule (monthly, quarterly, or annually).</li>
                <li>Property condition, interior features, and recent renovations are typically not captured in public data and may significantly affect actual value.</li>
                <li>Local factors such as neighborhood conditions, school quality changes, planned developments, and zoning amendments may not be reflected in the data in real time.</li>
              </ul>
              <p className="text-content-primary font-semibold">
                Users should independently verify all critical data before making any investment decisions. LootVue expressly disclaims any responsibility for decisions made based on inaccurate or incomplete data.
              </p>
            </section>

            {/* 7 */}
            <section>
              <h2 className="text-xl font-semibold text-white mb-4">Model Limitations</h2>
              <p className="mb-4">
                The analytical models and algorithms used by LootVue are simplifications of complex real-world systems. All models have inherent limitations and are based on assumptions that may not hold true in all circumstances. Model outputs are sensitive to input data quality, and small changes in inputs can sometimes produce significantly different outputs. Model performance may degrade during periods of unusual market conditions, structural economic changes, or in markets with limited data availability.
              </p>
              <p>
                We continuously work to improve our models and methodologies, but no model can perfectly predict future real estate market conditions or investment outcomes. The presence of a quantitative score or analysis should not be interpreted as an indication of higher certainty than is warranted by the underlying data and methodology.
              </p>
            </section>

            {/* 8 */}
            <section>
              <h2 className="text-xl font-semibold text-white mb-4">Third-Party Data and Links</h2>
              <p>
                The Service may contain data from third-party sources and links to third-party websites, tools, or services. LootVue does not endorse, control, or assume responsibility for the accuracy, completeness, or reliability of any third-party data or content. The inclusion of third-party data or links does not imply endorsement or affiliation. Your use of third-party services is subject to their respective terms and policies.
              </p>
            </section>

            {/* 9 */}
            <section>
              <h2 className="text-xl font-semibold text-white mb-4">Forward-Looking Statements</h2>
              <p>
                Certain features of the Service may present projections, forecasts, or forward-looking analyses regarding market trends, property values, rental income, or other financial metrics. These forward-looking statements are based on current data and assumptions and are inherently uncertain. Actual results may differ materially from any projections or estimates. Forward-looking statements should not be relied upon as predictions of future events or guarantees of future performance.
              </p>
            </section>

            {/* 10 */}
            <section>
              <h2 className="text-xl font-semibold text-white mb-4">Summary</h2>
              <div className="card border-white/10 p-5 space-y-3">
                <p className="flex items-start gap-2">
                  <span className="text-rose-light mt-0.5 flex-shrink-0">&bull;</span>
                  <span>LootVue is a data analytics platform, not an investment advisor.</span>
                </p>
                <p className="flex items-start gap-2">
                  <span className="text-rose-light mt-0.5 flex-shrink-0">&bull;</span>
                  <span>Nothing on this platform constitutes investment advice or a recommendation to buy or sell any property.</span>
                </p>
                <p className="flex items-start gap-2">
                  <span className="text-rose-light mt-0.5 flex-shrink-0">&bull;</span>
                  <span>All scores, verdicts, and confidence levels are algorithmic outputs, not guarantees.</span>
                </p>
                <p className="flex items-start gap-2">
                  <span className="text-rose-light mt-0.5 flex-shrink-0">&bull;</span>
                  <span>Past performance does not guarantee future results.</span>
                </p>
                <p className="flex items-start gap-2">
                  <span className="text-rose-light mt-0.5 flex-shrink-0">&bull;</span>
                  <span>Real estate investing involves significant risk, including potential loss of principal.</span>
                </p>
                <p className="flex items-start gap-2">
                  <span className="text-rose-light mt-0.5 flex-shrink-0">&bull;</span>
                  <span>Always consult qualified professionals before making investment decisions.</span>
                </p>
                <p className="flex items-start gap-2">
                  <span className="text-rose-light mt-0.5 flex-shrink-0">&bull;</span>
                  <span>Data may be incomplete, delayed, or inaccurate. Verify independently.</span>
                </p>
                <p className="flex items-start gap-2">
                  <span className="text-rose-light mt-0.5 flex-shrink-0">&bull;</span>
                  <span>LootVue is not registered with the SEC or any state regulatory authority.</span>
                </p>
              </div>
            </section>

            {/* Contact */}
            <section>
              <h2 className="text-xl font-semibold text-white mb-4">Contact Information</h2>
              <p className="mb-4">
                If you have questions about this Investment Disclaimer, please contact us:
              </p>
              <div className="card p-5 space-y-2">
                <p className="text-content-primary font-medium">LootVue Inc.</p>
                <p>Email: <a href="mailto:legal@lootvue.com" className="text-gold-light hover:text-white transition-colors underline underline-offset-2">legal@lootvue.com</a></p>
              </div>
            </section>

            {/* Related documents */}
            <section className="border-t border-white/[0.06] pt-10">
              <h2 className="text-lg font-semibold text-white mb-4">Related Legal Documents</h2>
              <div className="grid sm:grid-cols-2 gap-4">
                <Link href="/privacy" className="card-hover flex items-center gap-3 group">
                  <div className="w-10 h-10 rounded-lg bg-gold-muted flex items-center justify-center flex-shrink-0">
                    <span className="text-gold-light text-sm font-bold">P</span>
                  </div>
                  <div>
                    <div className="text-sm font-semibold text-white group-hover:text-gold-light transition-colors">Privacy Policy</div>
                    <div className="text-xs text-content-tertiary">How we collect and protect your data</div>
                  </div>
                </Link>
                <Link href="/terms" className="card-hover flex items-center gap-3 group">
                  <div className="w-10 h-10 rounded-lg bg-gold-muted flex items-center justify-center flex-shrink-0">
                    <span className="text-gold-light text-sm font-bold">T</span>
                  </div>
                  <div>
                    <div className="text-sm font-semibold text-white group-hover:text-gold-light transition-colors">Terms of Service</div>
                    <div className="text-xs text-content-tertiary">Terms governing use of the platform</div>
                  </div>
                </Link>
              </div>
            </section>

          </div>
        </div>
      </main>

      {/* ── FOOTER ── */}
      <footer className="border-t border-white/[0.06] py-16 px-6">
        <div className="max-w-7xl mx-auto">
          <div className="grid grid-cols-2 md:grid-cols-4 gap-8 mb-12">
            <div className="col-span-2 md:col-span-1">
              <Link href="/" className="flex items-center gap-2 mb-4">
                <span className="text-gold-light text-xl font-serif">LV</span>
                <span className="font-display font-bold text-white tracking-wider text-sm">LOOTVUE</span>
              </Link>
              <p className="text-xs text-content-tertiary leading-relaxed">
                Real estate intelligence for investors<br />who refuse to guess.
              </p>
            </div>
            {[
              { t: "Product", l: [{ name: "Features", href: "/#features" }, { name: "Pricing", href: "/#pricing" }] },
              { t: "Company", l: [{ name: "About", href: "#" }, { name: "Blog", href: "#" }] },
              { t: "Legal", l: [{ name: "Privacy", href: "/privacy" }, { name: "Terms", href: "/terms" }, { name: "Disclaimer", href: "/disclaimer" }] },
            ].map((c) => (
              <div key={c.t}>
                <div className="text-[11px] font-semibold text-content-tertiary uppercase tracking-wider mb-4">{c.t}</div>
                <ul className="space-y-2">{c.l.map((l) => <li key={l.name}><Link href={l.href} className="text-sm text-content-secondary hover:text-white transition-colors">{l.name}</Link></li>)}</ul>
              </div>
            ))}
          </div>
          <div className="border-t border-white/[0.06] pt-8 flex flex-col sm:flex-row items-center justify-between gap-4">
            <span className="text-xs text-content-disabled">&copy; 2026 LootVue Inc.</span>
            <span className="text-xs text-content-disabled">Data: FRED &middot; Census &middot; BLS &middot; ATTOM</span>
          </div>
        </div>
      </footer>
    </div>
  );
}
